export class EstoqueError {
  static readonly ESTOQUE_INSUFICIENTE = 'ESTOQUE_INSUFICIENTE'
  static readonly VARIACAO_NAO_ENCONTRADA = 'VARIACAO_NAO_ENCONTRADA'
  static readonly QUANTIDADE_INVALIDA = 'QUANTIDADE_INVALIDA'
  static readonly SALDO_INVALIDO = 'SALDO_INVALIDO'
  static readonly MOTIVO_MOVIMENTACAO_INVALIDO = 'MOTIVO_MOVIMENTACAO_INVALIDO'
  static readonly LEDGER_IMUTAVEL = 'LEDGER_IMUTAVEL'
}
