export class CaixaError {
  static readonly CASH_SESSION_ALREADY_OPEN = 'CASH_SESSION_ALREADY_OPEN'
  static readonly CASH_SESSION_NOT_FOUND = 'CASH_SESSION_NOT_FOUND'
  static readonly CASH_SESSION_ALREADY_CLOSED = 'CASH_SESSION_ALREADY_CLOSED'
  static readonly PENDING_SALE_IN_SESSION = 'PENDING_SALE_IN_SESSION'

  static readonly VALOR_ABERTURA_INVALIDO = 'VALOR_ABERTURA_INVALIDO'
  static readonly VALOR_FECHAMENTO_INVALIDO = 'VALOR_FECHAMENTO_INVALIDO'
  static readonly VALOR_MOVIMENTACAO_INVALIDO = 'VALOR_MOVIMENTACAO_INVALIDO'
}
